# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b4dfdbfeec8ebecb8107029c0a98408943104a72327da448d290aafd8d0e2473ec12a940e00c5f55915030cd0ab652cae6ae4ae9c5f66ac4ccb2d569dbed59b

test:
  secret_key_base: 20607f5ea563e068412d5dba163ae306dab3c8e1073a3e7b7f1a903c5db0b50abca575b7aefe167efd1f9c498f809129d796c4e96de48807d63d39fe1059a6ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
